### ISSUE TITLE
Inability to overwrite existing key values

### ISSUE THREAD

**Issue by primetoxinz** [rakusan2/FRC-NT-Client#2]
In [this example](https://gist.github.com/primetoxinz/c36e363187587daa310ac3068334793b), the NetworkTable will only get the first assigned value and will not be able to update afterwards. I believe this has something to do with [this line](https://github.com/rakusan2/FRC-NT-Client/blob/master/index.ts#L313) 
but I am not exactly sure why. Help would be appreciated.

**Comment by rakusan2** [comment]
Sorry for the late response,
The issue is not in the the line that you have specified since `keymap` holds keys mapped to id numbers which can only be assigned by the server.

The error lies in the code making multiple create variable requests to the server since currently `Assign` does not store any information and only makes create variable requests.
The server then sends me the ID of that variable and that is what I store in `keymap`.
If multiple create variable requests are made for the same key then the server only accepts the first one.

**Comment by rakusan2** [comment]
Your example should now work

**Comment by primetoxinz** [comment]
Just got around to testing this, the example still does not function. The first value is still the only value that reaches the server

**Comment by rakusan2** [comment]
I will look into it tomorrow

**Comment by rakusan2** [comment]
Thank you,
I have found and fixed two problems: 8932ed9
* keymap containing a map of vals to ids instead of keys to ids
* timer that delays writes to the server not being nulled after use

I have also added your example to the test file and tried it on a simulator
